<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Blokemon.App.Catalogue</RootNamespace>
    <AssemblyName>Blokemon.App.Catalogue</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Blokemon.App.Contracts/Blokemon.App.Contracts.csproj" />
    <ProjectReference Include="../Blokemon.Core/Blokemon.Core.csproj" />
  </ItemGroup>
</Project>
