<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Blokemon.Product/Blokemon.Product.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Shouldly" />
    <PackageReference Include="TUnit" />
  </ItemGroup>
  <ItemGroup>
    <Content
      Include="../../content/authorities/mechanics.json"
      Link="Authorities/mechanics.json"
      CopyToOutputDirectory="PreserveNewest"
    />
  </ItemGroup>
</Project>
