<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Blokemon.Web/Blokemon.Web.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="TUnit" />
  </ItemGroup>
  <ItemGroup>
    <Content
      Include="../../src/Blokemon.Web.Client/wwwroot/content/catalogue.json"
      Link="content/catalogue.json"
      CopyToOutputDirectory="PreserveNewest"
    />
    <Content
      Include="Fixtures/match-migrations/*.json"
      Link="match-migrations/%(Filename)%(Extension)"
      CopyToOutputDirectory="PreserveNewest"
    />
  </ItemGroup>
</Project>
