namespace Blokemon.Game

type CardKind =
    | Bloke = 0
    | Vim = 1
    | Kit = 2

type CardZone =
    | Stack = 0
    | Mitt = 1
    | Oche = 2
    | Booth = 3
    | Attached = 4
    | EmptiesTray = 5
    | Local = 6
    | BarChit = 7

type MatchPhase =
    | MulliganBonus = 0
    | OpeningPlacement = 1
    | Playing = 2
    | AwaitingEffectChoice = 3
    | AwaitingTriggerChoice = 4
    | AwaitingReplacement = 5
    | Complete = 6
    | BonusPlacement = 7

type DamageKind =
    | Attack = 0
    | BoothAttack = 1
    | PlacedCounter = 2
    | RoughState = 3
    | SelfDamage = 4

type DrawReason =
    | OpeningMitt = 0
    | MulliganBonus = 1
    | RequiredRoundDraw = 2
    | Effect = 3

type TemporaryEffectKind =
    | PreventDamage = 0
    | PreventEffects = 1
    | ReduceDamage = 2
    | ModifyAttackCost = 3
    | ModifyTaxiFare = 4
    | ModifyStayingPower = 5
    | ModifySoftSpot = 6
    | IgnoreStubbornStreak = 7
    | IgnoreSoftSpotAndStubbornStreak = 8
    | RestrictAttack = 9
    | RestrictAttackOnBeerMat = 10
    | RestrictTaxi = 11
    | RestrictKit = 12
    | RestrictLocal = 13
    | RestrictEmptiesRecovery = 14
    | ForceBeerMatBlank = 15
    | ReflectAttackDamage = 16
    | ScaleNextAttackDamage = 17
    | ContinuousPartyTrick = 18
    | EndRoundEffect = 19

type EffectDuration =
    | CurrentResolution = 0
    | UntilEndOfRound = 1
    | UntilEndOfOpponentsNextRound = 2
    | WhileSourceInPlay = 3
    | WhileTargetInPlay = 4

type MatchEventKind =
    | MatchStarted = 0
    | CommandApplied = 1
    | CardsShuffled = 2
    | CardsDrawn = 3
    | CardMoved = 4
    | CardsRevealed = 5
    | BeerMatTossed = 6
    | DamagePlaced = 7
    | DamageHealed = 8
    | RoughStateApplied = 9
    | RoughStateCleared = 10
    | EffectRegistered = 11
    | EffectChoiceRequested = 12
    | TriggerQueued = 13
    | TriggerResolved = 14
    | AttackDeclared = 15
    | AttackCancelled = 16
    | BlokeSentHome = 17
    | BarChitsTaken = 18
    | RoundStarted = 19
    | RoundEnded = 20
    | SuddenDeathStarted = 21
    | MatchWon = 22
    | StateCommitted = 23
    | OcheSwapped = 24

type DeckIssueCode =
    | InvalidMatchId = 0
    | InvalidPlayerId = 1
    | DuplicatePlayer = 2
    | WrongCardCount = 3
    | UnknownMechanicalCard = 4
    | TooManyCopies = 5
    | MissingRegularBloke = 6
    | AuthorityInvalid = 7

type CommandRejectionCode =
    | WrongMatch = 0
    | StaleRevision = 1
    | UnknownActor = 2
    | WrongPhase = 3
    | NotActorsTurn = 4
    | CardNotFound = 5
    | CardNotOwned = 6
    | WrongZone = 7
    | WrongCardKind = 8
    | RuleLimitReached = 9
    | IllegalOpening = 10
    | IneligiblePromotion = 11
    | InsufficientVim = 12
    | InvalidTaxiFare = 13
    | EffectNotFound = 14
    | EffectUnavailable = 15
    | ChoiceRequired = 16
    | InvalidChoice = 17
    | MatchComplete = 18
    | AuthorityMismatch = 19
    | DuplicateCommand = 20
    | WrongChooser = 21

type ChoiceRequirementKind =
    | Optional = 0
    | Amount = 1
    | Cards = 2
    | MechanicalType = 3
    | Attack = 4
    | Distribution = 5
    | Attachments = 6

type LegalActionKind =
    | ChooseMulliganBonus = 0
    | ChooseOpening = 1
    | ChooseReplacement = 2
    | AttachVim = 3
    | PlayBloke = 4
    | Promote = 5
    | PlayKit = 6
    | UsePartyTrick = 7
    | Attack = 8
    | Taxi = 9
    | ChuckFossil = 10
    | EndRound = 11
    | ResolveEffectChoice = 12
    | ResolveKnockoutTrigger = 13
    | ResolveBarChitTrigger = 14
    | Resign = 15
    | ChooseBonusPlacement = 16
