<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Blokemon.Web.Client</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" />
    <ProjectReference Include="../../src/Blokemon.App.Contracts/Blokemon.App.Contracts.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile
      Include="../../src/Blokemon.Web.Client/Components/CardHold.cs"
      Link="Components/CardHold.cs"
    />
    <Compile
      Include="../../src/Blokemon.Web.Client/Components/CardFaceSize.cs"
      Link="Components/CardFaceSize.cs"
    />
    <Compile
      Include="../../src/Blokemon.Web.Client/Components/MatchText.cs"
      Link="Components/MatchText.cs"
    />
    <Compile
      Include="../../src/Blokemon.Web.Client/Components/MatchAttachedCards.cs"
      Link="Components/MatchAttachedCards.cs"
    />
    <Compile
      Include="../../src/Blokemon.Web.Client/Components/MatchAuraView.cs"
      Link="Components/MatchAuraView.cs"
    />
    <Compile
      Include="../../src/Blokemon.Web.Client/Components/MatchSheetView.cs"
      Link="Components/MatchSheetView.cs"
    />
    <Compile
      Include="../../src/Blokemon.Web.Client/Components/MatchTable.cs"
      Link="Components/MatchTable.cs"
    />
    <RazorComponent
      Include="../../src/Blokemon.Web.Client/Components/BlokemonChip.razor"
      Link="Components/BlokemonChip.razor"
    />
    <RazorComponent
      Include="../../src/Blokemon.Web.Client/Components/CardFace.razor"
      Link="Components/CardFace.razor"
    />
    <RazorComponent
      Include="../../src/Blokemon.Web.Client/Components/CardPress.razor"
      Link="Components/CardPress.razor"
    />
    <RazorComponent
      Include="../../src/Blokemon.Web.Client/Components/CardReader.razor"
      Link="Components/CardReader.razor"
    />
    <RazorComponent
      Include="../../src/Blokemon.Web.Client/Components/CardViewer.razor"
      Link="Components/CardViewer.razor"
    />
    <RazorComponent
      Include="../../src/Blokemon.Web.Client/Components/CardViewerHost.razor"
      Link="Components/CardViewerHost.razor"
    />
    <RazorComponent
      Include="../../src/Blokemon.Web.Client/Components/MatchCueOverlays.razor"
      Link="Components/MatchCueOverlays.razor"
    />
    <RazorComponent
      Include="../../src/Blokemon.Web.Client/Components/MatchActionDock.razor"
      Link="Components/MatchActionDock.razor"
    />
    <RazorComponent
      Include="../../src/Blokemon.Web.Client/Components/MatchActionSheet.razor"
      Link="Components/MatchActionSheet.razor"
    />
  </ItemGroup>
  <ItemGroup>
    <Content
      Include="../../src/Blokemon.Web/wwwroot/css/**"
      Link="wwwroot/css/%(RecursiveDir)%(Filename)%(Extension)"
    />
    <Content
      Include="../../src/Blokemon.Web.Client/wwwroot/cardViewer.js"
      Link="wwwroot/cardViewer.js"
    />
  </ItemGroup>
</Project>
